### ISSUE TITLE
使用Docker搭建自己的Sentry服务 | HuiBlog

### ISSUE THREAD

**Issue by kjh123** [kjh123/kjh123.github.io#17]
https://hui.1222.store/2018/12/10/%E4%BD%BF%E7%94%A8Docker%E6%90%AD%E5%BB%BA%E8%87%AA%E5%B7%B1%E7%9A%84Sentry%E6%9C%8D%E5%8A%A1/

**Comment by yushaolong10** [comment]
赞！
